
Login-AzureRmAccount;

New-AzureRmResourceGroupDeployment -ResourceGroupName jmdbecaresourcegroup -TemplateFile jmdbecaappserviceServiceBus.json -namespaces_servicebusjmd_name jmdbecaappserviceServiceBus -queues_iothubque_name jmdbecaappserviceServiceBusQueue;
