//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

[module: global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "Compañía.IotDsl.IotDslDiagram")]

namespace Compañía.IotDsl
{
	/// <summary>
	/// DomainClass IotDslDiagram
	/// Description for Compañía.IotDsl.IotDslDiagram
	/// </summary>
	[DslDesign::DisplayNameResource("Compañía.IotDsl.IotDslDiagram.DisplayName", typeof(global::Compañía.IotDsl.IotDslDomainModel), "Compañía.IotDsl.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Compañía.IotDsl.IotDslDiagram.Description", typeof(global::Compañía.IotDsl.IotDslDomainModel), "Compañía.IotDsl.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::Compañía.IotDsl.IotDslDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("32697784-6bc9-41c1-9b38-d506ffa3b791")]
	public partial class IotDslDiagram : DslDiagrams::Diagram
	{
		#region Diagram boilerplate
		private static DslDiagrams::StyleSet classStyleSet;
		private static global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields;
		/// <summary>
		/// Per-class style set for this shape.
		/// </summary>
		protected override DslDiagrams::StyleSet ClassStyleSet
		{
			get
			{
				if (classStyleSet == null)
				{
					classStyleSet = CreateClassStyleSet();
				}
				return classStyleSet;
			}
		}
		
		/// <summary>
		/// Per-class ShapeFields for this shape
		/// </summary>
		public override global::System.Collections.Generic.IList<DslDiagrams::ShapeField> ShapeFields
		{
			get
			{
				if (shapeFields == null)
				{
					shapeFields = CreateShapeFields();
				}
				return shapeFields;
			}
		}
		#endregion
		#region Toolbox filters
		private static global::System.ComponentModel.ToolboxItemFilterAttribute[] toolboxFilters = new global::System.ComponentModel.ToolboxItemFilterAttribute[] {
					new global::System.ComponentModel.ToolboxItemFilterAttribute(global::Compañía.IotDsl.IotDslToolboxHelperBase.ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) };
		
		/// <summary>
		/// Toolbox item filter attributes for this diagram.
		/// </summary>
		public override global::System.Collections.ICollection TargetToolboxItemFilterAttributes
		{
			get
			{
				return toolboxFilters;
			}
		}
		#endregion
		#region Auto-placement
		/// <summary>
		/// Indicate that child shapes should added through view fixup should be placed automatically.
		/// </summary>
		public override bool ShouldAutoPlaceChildShapes
		{
			get
			{
				return true;
			}
		}
		#endregion
		#region Shape mapping
		/// <summary>
		/// Called during view fixup to ask the parent whether a shape should be created for the given child element.
		/// </summary>
		/// <remarks>
		/// Always return true, since we assume there is only one diagram per model file for DSL scenarios.
		/// </remarks>
		protected override bool ShouldAddShapeForElement(DslModeling::ModelElement element)
		{
			return true;
		}
		
		/// <summary>
		/// Called during view fixup to configure the given child element, after it has been created.
		/// </summary>
		/// <remarks>
		/// Custom code for choosing the shapes attached to either end of a connector is called from here.
		/// </remarks>
		protected override void OnChildConfiguring(DslDiagrams::ShapeElement child, bool createdDuringViewFixup)
		{
			DslDiagrams::NodeShape sourceShape;
			DslDiagrams::NodeShape targetShape;
			DslDiagrams::BinaryLinkShape connector = child as DslDiagrams::BinaryLinkShape;
			if(connector == null)
			{
				base.OnChildConfiguring(child, createdDuringViewFixup);
				return;
			}
			this.GetSourceAndTargetForConnector(connector, out sourceShape, out targetShape);
			
			global::System.Diagnostics.Debug.Assert(sourceShape != null && targetShape != null, "Unable to find source and target shapes for connector.");
			connector.Connect(sourceShape, targetShape);
		}
		
		/// <summary>
		/// helper method to find the shapes for either end of a connector, including calling the user's custom code
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		internal void GetSourceAndTargetForConnector(DslDiagrams::BinaryLinkShape connector, out DslDiagrams::NodeShape sourceShape, out DslDiagrams::NodeShape targetShape)
		{
			sourceShape = null;
			targetShape = null;
			
			if (sourceShape == null || targetShape == null)
			{
				DslDiagrams::NodeShape[] endShapes = GetEndShapesForConnector(connector);
				if(sourceShape == null)
				{
					sourceShape = endShapes[0];
				}
				if(targetShape == null)
				{
					targetShape = endShapes[1];
				}
			}
		}
		
		/// <summary>
		/// Helper method to find shapes for either end of a connector by looking for shapes associated with either end of the relationship mapped to the connector.
		/// </summary>
		private DslDiagrams::NodeShape[] GetEndShapesForConnector(DslDiagrams::BinaryLinkShape connector)
		{
			DslModeling::ElementLink link = connector.ModelElement as DslModeling::ElementLink;
			DslDiagrams::NodeShape sourceShape = null, targetShape = null;
			if (link != null)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = link.LinkedElements;
				if (linkedElements.Count == 2)
				{
					DslDiagrams::Diagram currentDiagram = this.Diagram;
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							sourceShape = shape;
							break;
						}
					}
					
					presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							targetShape = shape;
							break;
						}
					}
		
				}
			}
			
			return new DslDiagrams::NodeShape[] { sourceShape, targetShape };
		}
		
		/// <summary>
		/// Creates a new shape for the given model element as part of view fixup
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Justification = "Generated code.")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
		protected override DslDiagrams::ShapeElement CreateChildShape(DslModeling::ModelElement element)
		{
			if(element is global::Compañía.IotDsl.GrupoDeRecursos)
			{
				global::Compañía.IotDsl.GrupoDeRecursosShape newShape = new global::Compañía.IotDsl.GrupoDeRecursosShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Compañía.IotDsl.CentroIoT)
			{
				global::Compañía.IotDsl.CentroIoTImage newShape = new global::Compañía.IotDsl.CentroIoTImage(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Compañía.IotDsl.MessagingasaService)
			{
				global::Compañía.IotDsl.MAASImage newShape = new global::Compañía.IotDsl.MAASImage(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Compañía.IotDsl.DataAnalytics)
			{
				global::Compañía.IotDsl.DataAnalyticsImage newShape = new global::Compañía.IotDsl.DataAnalyticsImage(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Compañía.IotDsl.AlmacenamientoNoSQL)
			{
				global::Compañía.IotDsl.AlamcenamientoNoSQLImage newShape = new global::Compañía.IotDsl.AlamcenamientoNoSQLImage(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Compañía.IotDsl.VisualizaconDatos)
			{
				global::Compañía.IotDsl.VisualizacionImagen newShape = new global::Compañía.IotDsl.VisualizacionImagen(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Compañía.IotDsl.CentroIoTReferenciasMessagingasaService)
			{
				global::Compañía.IotDsl.ConexionIotHubMAAS newShape = new global::Compañía.IotDsl.ConexionIotHubMAAS(this.Partition);
				return newShape;
			}
			if(element is global::Compañía.IotDsl.EntradaIotHub)
			{
				global::Compañía.IotDsl.EntradaIoTDataAnalytics newShape = new global::Compañía.IotDsl.EntradaIoTDataAnalytics(this.Partition);
				return newShape;
			}
			if(element is global::Compañía.IotDsl.SalidaAlmacenamientoNoSQL)
			{
				global::Compañía.IotDsl.SalidaNoSQLDataAnalytics newShape = new global::Compañía.IotDsl.SalidaNoSQLDataAnalytics(this.Partition);
				return newShape;
			}
			if(element is global::Compañía.IotDsl.MessagingasaServiceReferenciasVisualizaconDatos)
			{
				global::Compañía.IotDsl.ConexionMAASVisualizacion newShape = new global::Compañía.IotDsl.ConexionMAASVisualizacion(this.Partition);
				return newShape;
			}
			return base.CreateChildShape(element);
		}
		#endregion
		#region Decorator mapping
		/// <summary>
		/// Initialize shape decorator mappings.  This is done here rather than in individual shapes because decorator maps
		/// are defined per diagram type rather than per shape type.
		/// </summary>
		protected override void InitializeShapeFields(global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields)
		{
			base.InitializeShapeFields(shapeFields);
			global::Compañía.IotDsl.GrupoDeRecursosShape.DecoratorsInitialized += GrupoDeRecursosShapeDecoratorMap.OnDecoratorsInitialized;
			global::Compañía.IotDsl.CentroIoTImage.DecoratorsInitialized += CentroIoTImageDecoratorMap.OnDecoratorsInitialized;
			global::Compañía.IotDsl.MAASImage.DecoratorsInitialized += MAASImageDecoratorMap.OnDecoratorsInitialized;
			global::Compañía.IotDsl.DataAnalyticsImage.DecoratorsInitialized += DataAnalyticsImageDecoratorMap.OnDecoratorsInitialized;
			global::Compañía.IotDsl.AlamcenamientoNoSQLImage.DecoratorsInitialized += AlamcenamientoNoSQLImageDecoratorMap.OnDecoratorsInitialized;
			global::Compañía.IotDsl.VisualizacionImagen.DecoratorsInitialized += VisualizacionImagenDecoratorMap.OnDecoratorsInitialized;
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for GrupoDeRecursosShape.
		/// </summary>
		internal static partial class GrupoDeRecursosShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for GrupoDeRecursosShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Compañía.IotDsl.GrupoDeRecursos.NombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Nombre").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for CentroIoTImage.
		/// </summary>
		internal static partial class CentroIoTImageDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for CentroIoTImage.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Compañía.IotDsl.CentroIoT.NombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Nombre").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MAASImage.
		/// </summary>
		internal static partial class MAASImageDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MAASImage.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Compañía.IotDsl.MessagingasaService.NombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Nombre").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for DataAnalyticsImage.
		/// </summary>
		internal static partial class DataAnalyticsImageDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for DataAnalyticsImage.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Compañía.IotDsl.DataAnalytics.NombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Nombre").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for AlamcenamientoNoSQLImage.
		/// </summary>
		internal static partial class AlamcenamientoNoSQLImageDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for AlamcenamientoNoSQLImage.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Compañía.IotDsl.AlmacenamientoNoSQL.NombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Nombre").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for VisualizacionImagen.
		/// </summary>
		internal static partial class VisualizacionImagenDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for VisualizacionImagen.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Compañía.IotDsl.VisualizaconDatos.NombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Nombre").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		#endregion
		
		#region Connect actions
		private bool changingMouseAction;
		private global::Compañía.IotDsl.ConexionIotHubServiceBusToolConnectAction conexionIotHubServiceBusToolConnectAction;
		private global::Compañía.IotDsl.EntradaIoTDataAnalyticsConnectAction entradaIoTDataAnalyticsConnectAction;
		private global::Compañía.IotDsl.SalidaNoSqlDataAnalyticsConnectAction salidaNoSqlDataAnalyticsConnectAction;
		private global::Compañía.IotDsl.ConexionMAASVisualizacionConnectAction conexionMAASVisualizacionConnectAction;
		/// <summary>
		/// Virtual method to provide a filter when to select the mouse action
		/// </summary>
		/// <param name="activeView">Currently active view</param>
		/// <param name="filter">filter string used to filter the toolbox items</param>
		protected virtual bool SelectedToolboxItemSupportsFilterString(DslDiagrams::DiagramView activeView, string filter)
		{
			return activeView.SelectedToolboxItemSupportsFilterString(filter);
		}
		/// <summary>
		/// Override to provide the right mouse action when trying
		/// to create links on the diagram
		/// </summary>
		/// <param name="pointArgs"></param>
		public override void OnViewMouseEnter(DslDiagrams::DiagramPointEventArgs pointArgs)
		{
			if (pointArgs  == null) throw new global::System.ArgumentNullException("pointArgs");
		
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
			if(activeView != null)
			{
				DslDiagrams::MouseAction action = null;
				if (SelectedToolboxItemSupportsFilterString(activeView, global::Compañía.IotDsl.IotDslToolboxHelper.ConexionIotHubServiceBusToolFilterString))
				{
					if (this.conexionIotHubServiceBusToolConnectAction == null)
					{
						this.conexionIotHubServiceBusToolConnectAction = new global::Compañía.IotDsl.ConexionIotHubServiceBusToolConnectAction(this);
						this.conexionIotHubServiceBusToolConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.conexionIotHubServiceBusToolConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::Compañía.IotDsl.IotDslToolboxHelper.EntradaIoTDataAnalyticsFilterString))
				{
					if (this.entradaIoTDataAnalyticsConnectAction == null)
					{
						this.entradaIoTDataAnalyticsConnectAction = new global::Compañía.IotDsl.EntradaIoTDataAnalyticsConnectAction(this);
						this.entradaIoTDataAnalyticsConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.entradaIoTDataAnalyticsConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::Compañía.IotDsl.IotDslToolboxHelper.SalidaNoSqlDataAnalyticsFilterString))
				{
					if (this.salidaNoSqlDataAnalyticsConnectAction == null)
					{
						this.salidaNoSqlDataAnalyticsConnectAction = new global::Compañía.IotDsl.SalidaNoSqlDataAnalyticsConnectAction(this);
						this.salidaNoSqlDataAnalyticsConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.salidaNoSqlDataAnalyticsConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::Compañía.IotDsl.IotDslToolboxHelper.ConexionMAASVisualizacionFilterString))
				{
					if (this.conexionMAASVisualizacionConnectAction == null)
					{
						this.conexionMAASVisualizacionConnectAction = new global::Compañía.IotDsl.ConexionMAASVisualizacionConnectAction(this);
						this.conexionMAASVisualizacionConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.conexionMAASVisualizacionConnectAction;
				} 
				else
				{
					action = null;
				}
				
				if (pointArgs.DiagramClientView.ActiveMouseAction != action)
				{
					try
					{
						this.changingMouseAction = true;
						pointArgs.DiagramClientView.ActiveMouseAction = action;
					}
					finally
					{
						this.changingMouseAction = false;
					}
				}
			}
		}
		
		/// <summary>
		/// Snap toolbox selection back to regular pointer after using a custom connect action.
		/// </summary>
		private void OnConnectActionDeactivated(object sender, DslDiagrams::DiagramEventArgs e)
		{
			OnMouseActionDeactivated();
		}
		
		/// <summary>
		/// Overridable method to manage the mouse deactivation. The default implementation snap stoolbox selection back to regular pointer 
		/// after using a custom connect action.
		/// </summary>
		protected virtual void OnMouseActionDeactivated()
		{
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
		
			if (activeView != null && activeView.Toolbox != null)
			{
				// If we're not changing mouse action due to changing toolbox selection change,
				// reset toolbox selection.
				if (!this.changingMouseAction)
				{
					activeView.Toolbox.SelectedToolboxItemUsed();
				}
			}
		}
		#endregion
		
		/// <summary>
		/// Dispose of connect actions.
		/// </summary>
		protected override void Dispose(bool disposing)
		{
			try
			{
				if(disposing)
				{
					if(this.conexionIotHubServiceBusToolConnectAction != null)
					{
						this.conexionIotHubServiceBusToolConnectAction.Dispose();
						this.conexionIotHubServiceBusToolConnectAction = null;
					}
					if(this.entradaIoTDataAnalyticsConnectAction != null)
					{
						this.entradaIoTDataAnalyticsConnectAction.Dispose();
						this.entradaIoTDataAnalyticsConnectAction = null;
					}
					if(this.salidaNoSqlDataAnalyticsConnectAction != null)
					{
						this.salidaNoSqlDataAnalyticsConnectAction.Dispose();
						this.salidaNoSqlDataAnalyticsConnectAction = null;
					}
					if(this.conexionMAASVisualizacionConnectAction != null)
					{
						this.conexionMAASVisualizacionConnectAction.Dispose();
						this.conexionMAASVisualizacionConnectAction = null;
					}
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}
		#region Constructors, domain class Id
	
		/// <summary>
		/// IotDslDiagram domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x32697784, 0x6bc9, 0x41c1, 0x9b, 0x38, 0xd5, 0x06, 0xff, 0xa3, 0xb7, 0x91);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public IotDslDiagram(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public IotDslDiagram(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace Compañía.IotDsl
{
	
		/// <summary>
		/// Double derived implementation for the rule that initiates view fixup when an element that has an associated shape is added to the model.
		/// This now enables the DSL author to everride the SkipFixUp() method 
		/// </summary>
		internal partial class FixUpDiagramBase : DslModeling::AddRule
		{
			protected virtual bool SkipFixup(DslModeling::ModelElement childElement)
			{
				return childElement.IsDeleted;
			}
		}
	
		/// <summary>
		/// Rule that initiates view fixup when an element that has an associated shape is added to the model. 
		/// </summary>
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.GrupoDeRecursos), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.CentroIoT), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.MessagingasaService), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.DataAnalytics), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.AlmacenamientoNoSQL), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.VisualizaconDatos), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.CentroIoTReferenciasMessagingasaService), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.EntradaIotHub), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.SalidaAlmacenamientoNoSQL), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.MessagingasaServiceReferenciasVisualizaconDatos), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed partial class FixUpDiagram : FixUpDiagramBase
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
			
				DslModeling::ModelElement childElement = e.ModelElement;
				if (this.SkipFixup(childElement))
					return;
				DslModeling::ModelElement parentElement;
				if(childElement is DslModeling::ElementLink)
				{
					parentElement = GetParentForRelationship((DslModeling::ElementLink)childElement);
				} else
				if(childElement is global::Compañía.IotDsl.GrupoDeRecursos)
				{
					parentElement = GetParentForGrupoDeRecursos((global::Compañía.IotDsl.GrupoDeRecursos)childElement);
				} else
				if(childElement is global::Compañía.IotDsl.CentroIoT)
				{
					parentElement = GetParentForCentroIoT((global::Compañía.IotDsl.CentroIoT)childElement);
				} else
				if(childElement is global::Compañía.IotDsl.MessagingasaService)
				{
					parentElement = GetParentForMessagingasaService((global::Compañía.IotDsl.MessagingasaService)childElement);
				} else
				if(childElement is global::Compañía.IotDsl.DataAnalytics)
				{
					parentElement = GetParentForDataAnalytics((global::Compañía.IotDsl.DataAnalytics)childElement);
				} else
				if(childElement is global::Compañía.IotDsl.AlmacenamientoNoSQL)
				{
					parentElement = GetParentForAlmacenamientoNoSQL((global::Compañía.IotDsl.AlmacenamientoNoSQL)childElement);
				} else
				if(childElement is global::Compañía.IotDsl.VisualizaconDatos)
				{
					parentElement = GetParentForVisualizaconDatos((global::Compañía.IotDsl.VisualizaconDatos)childElement);
				} else
				{
					parentElement = null;
				}
				
				if(parentElement != null)
				{
					DslDiagrams::Diagram.FixUpDiagram(parentElement, childElement);
				}
			}
			public static global::Compañía.IotDsl.IotDsl1 GetParentForGrupoDeRecursos( global::Compañía.IotDsl.GrupoDeRecursos root )
			{
				// Segments 0 and 1
				global::Compañía.IotDsl.IotDsl1 result = root.IotDsl1;
				if ( result == null ) return null;
				return result;
			}
			public static global::Compañía.IotDsl.IotDsl1 GetParentForCentroIoT( global::Compañía.IotDsl.CentroIoT root )
			{
				// Segments 0 and 1
				global::Compañía.IotDsl.GrupoDeRecursos root2 = root.GrupoDeRecursos;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::Compañía.IotDsl.IotDsl1 result = root2.IotDsl1;
				if ( result == null ) return null;
				return result;
			}
			public static global::Compañía.IotDsl.IotDsl1 GetParentForMessagingasaService( global::Compañía.IotDsl.MessagingasaService root )
			{
				// Segments 0 and 1
				global::Compañía.IotDsl.GrupoDeRecursos root2 = root.GrupoDeRecursos;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::Compañía.IotDsl.IotDsl1 result = root2.IotDsl1;
				if ( result == null ) return null;
				return result;
			}
			public static global::Compañía.IotDsl.IotDsl1 GetParentForDataAnalytics( global::Compañía.IotDsl.DataAnalytics root )
			{
				// Segments 0 and 1
				global::Compañía.IotDsl.GrupoDeRecursos root2 = root.GrupoDeRecursos;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::Compañía.IotDsl.IotDsl1 result = root2.IotDsl1;
				if ( result == null ) return null;
				return result;
			}
			public static global::Compañía.IotDsl.IotDsl1 GetParentForAlmacenamientoNoSQL( global::Compañía.IotDsl.AlmacenamientoNoSQL root )
			{
				// Segments 0 and 1
				global::Compañía.IotDsl.GrupoDeRecursos root2 = root.GrupoDeRecursos;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::Compañía.IotDsl.IotDsl1 result = root2.IotDsl1;
				if ( result == null ) return null;
				return result;
			}
			public static global::Compañía.IotDsl.IotDsl1 GetParentForVisualizaconDatos( global::Compañía.IotDsl.VisualizaconDatos root )
			{
				// Segments 0 and 1
				global::Compañía.IotDsl.GrupoDeRecursos root2 = root.GrupoDeRecursos;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::Compañía.IotDsl.IotDsl1 result = root2.IotDsl1;
				if ( result == null ) return null;
				return result;
			}
			private static DslModeling::ModelElement GetParentForRelationship(DslModeling::ElementLink elementLink)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = elementLink.LinkedElements;
	
				if (linkedElements.Count == 2)
				{
					DslDiagrams::ShapeElement sourceShape = linkedElements[0] as DslDiagrams::ShapeElement;
					DslDiagrams::ShapeElement targetShape = linkedElements[1] as DslDiagrams::ShapeElement;
	
					if(sourceShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								sourceShape = shape;
								break;
							}
						}
					}
					
					if(targetShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								targetShape = shape;
								break;
							}
						}
					}
					
					if(sourceShape == null || targetShape == null)
					{
						global::System.Diagnostics.Debug.Fail("Unable to find source and/or target shape for view fixup.");
						return null;
					}
	
					DslDiagrams::ShapeElement sourceParent = sourceShape.ParentShape;
					DslDiagrams::ShapeElement targetParent = targetShape.ParentShape;
	
					while (sourceParent != targetParent && sourceParent != null)
					{
						DslDiagrams::ShapeElement curParent = targetParent;
						while (sourceParent != curParent && curParent != null)
						{
							curParent = curParent.ParentShape;
						}
	
						if(sourceParent == curParent)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					while (sourceParent != null)
					{
						// ensure that the parent can parent connectors (i.e., a diagram or a swimlane).
						if(sourceParent is DslDiagrams::Diagram || sourceParent is DslDiagrams::SwimlaneShape)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					global::System.Diagnostics.Debug.Assert(sourceParent != null && sourceParent.ModelElement != null, "Unable to find common parent for view fixup.");
					return sourceParent.ModelElement;
				}
	
				return null;
			}
		}
		
	
		/// <summary>
		/// A rule which fires when data mapped to outer text decorators has changed,
		/// so we can update the decorator host's bounds.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.CentroIoT), InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.MessagingasaService), InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.DataAnalytics), InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.AlmacenamientoNoSQL), InitiallyDisabled=true)]
		internal sealed class DecoratorPropertyChanged : DslModeling::ChangeRule
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Justification = "Generated code.")]
			public override void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
				
				if (e.DomainProperty.Id == global::Compañía.IotDsl.CentroIoT.NombreDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::Compañía.IotDsl.CentroIoTImage.FindCentroIoTImageDecorator("Nombre");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::Compañía.IotDsl.CentroIoT.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::Compañía.IotDsl.MessagingasaService.NombreDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::Compañía.IotDsl.MAASImage.FindMAASImageDecorator("Nombre");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::Compañía.IotDsl.MessagingasaService.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::Compañía.IotDsl.DataAnalytics.NombreDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::Compañía.IotDsl.DataAnalyticsImage.FindDataAnalyticsImageDecorator("Nombre");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::Compañía.IotDsl.DataAnalytics.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::Compañía.IotDsl.AlmacenamientoNoSQL.NombreDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::Compañía.IotDsl.AlamcenamientoNoSQLImage.FindAlamcenamientoNoSQLImageDecorator("Nombre");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::Compañía.IotDsl.AlmacenamientoNoSQL.DomainClassId);
					}
				}
			}
		}
	
		/// <summary>
		/// Reroute a connector when the role players of its underlying relationship change
		/// </summary>
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.CentroIoTReferenciasMessagingasaService), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.EntradaIotHub), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.SalidaAlmacenamientoNoSQL), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.MessagingasaServiceReferenciasVisualizaconDatos), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed class ConnectorRolePlayerChanged : DslModeling::RolePlayerChangeRule
		{
			/// <summary>
			/// Reroute a connector when the role players of its underlying relationship change
			/// </summary>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				if (e == null) throw new global::System.ArgumentNullException("e");
	
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslDiagrams::PresentationViewsSubject> connectorLinks = DslDiagrams::PresentationViewsSubject.GetLinksToPresentation(e.ElementLink);
				foreach (DslDiagrams::PresentationViewsSubject connectorLink in connectorLinks)
				{
					// Fix up any binary link shapes attached to the element link.
					DslDiagrams::BinaryLinkShape linkShape = connectorLink.Presentation as DslDiagrams::BinaryLinkShape;
					if (linkShape != null)
					{
						global::Compañía.IotDsl.IotDslDiagram diagram = linkShape.Diagram as global::Compañía.IotDsl.IotDslDiagram;
						if (diagram != null)
						{
							if (e.NewRolePlayer != null)
							{
								DslDiagrams::NodeShape fromShape;
								DslDiagrams::NodeShape toShape;
								diagram.GetSourceAndTargetForConnector(linkShape, out fromShape, out toShape);
								if (fromShape != null && toShape != null)
								{
									if (!object.Equals(fromShape, linkShape.FromShape))
									{
										linkShape.FromShape = fromShape;
									}
									if (!object.Equals(linkShape.ToShape, toShape))
									{
										linkShape.ToShape = toShape;
									}
								}
								else
								{
									// delete the connector if we cannot find an appropriate target shape.
									linkShape.Delete();
								}
							}
							else
							{
								// delete the connector if the new role player is null.
								linkShape.Delete();
							}
						}
					}
				}
			}
		}
	}
