//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

[module: global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "Compañía.IotDsl.IotDslDiagram")]

namespace Compañía.IotDsl
{
	/// <summary>
	/// DomainClass IotDslDiagram
	/// Description for Compañía.IotDsl.IotDslDiagram
	/// </summary>
	[DslDesign::DisplayNameResource("Compañía.IotDsl.IotDslDiagram.DisplayName", typeof(global::Compañía.IotDsl.IotDslDomainModel), "Compañía.IotDsl.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Compañía.IotDsl.IotDslDiagram.Description", typeof(global::Compañía.IotDsl.IotDslDomainModel), "Compañía.IotDsl.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::Compañía.IotDsl.IotDslDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("32697784-6bc9-41c1-9b38-d506ffa3b791")]
	public partial class IotDslDiagram : DslDiagrams::Diagram
	{
		#region Diagram boilerplate
		private static DslDiagrams::StyleSet classStyleSet;
		private static global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields;
		/// <summary>
		/// Per-class style set for this shape.
		/// </summary>
		protected override DslDiagrams::StyleSet ClassStyleSet
		{
			get
			{
				if (classStyleSet == null)
				{
					classStyleSet = CreateClassStyleSet();
				}
				return classStyleSet;
			}
		}
		
		/// <summary>
		/// Per-class ShapeFields for this shape
		/// </summary>
		public override global::System.Collections.Generic.IList<DslDiagrams::ShapeField> ShapeFields
		{
			get
			{
				if (shapeFields == null)
				{
					shapeFields = CreateShapeFields();
				}
				return shapeFields;
			}
		}
		#endregion
		#region Toolbox filters
		private static global::System.ComponentModel.ToolboxItemFilterAttribute[] toolboxFilters = new global::System.ComponentModel.ToolboxItemFilterAttribute[] {
					new global::System.ComponentModel.ToolboxItemFilterAttribute(global::Compañía.IotDsl.IotDslToolboxHelperBase.ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) };
		
		/// <summary>
		/// Toolbox item filter attributes for this diagram.
		/// </summary>
		public override global::System.Collections.ICollection TargetToolboxItemFilterAttributes
		{
			get
			{
				return toolboxFilters;
			}
		}
		#endregion
		#region Auto-placement
		/// <summary>
		/// Indicate that child shapes should added through view fixup should be placed automatically.
		/// </summary>
		public override bool ShouldAutoPlaceChildShapes
		{
			get
			{
				return true;
			}
		}
		#endregion
		#region Port shape support
		/// <summary>
		/// Indicates whether the diagram contains any ports.  Hit testing will not
		/// check for ports if this is false.
		/// </summary>
		public override bool SupportsPorts
		{
			get
			{
				return true;
			}
		}
		#endregion
		#region Compartment support
		/// <summary>
		/// Whether compartment items change events are subscribed to.
		/// </summary>
		private bool subscribedCompartmentItemsEvents;
		
		/// <summary>
		/// Subscribe to events fired when compartment items changes.
		/// </summary>
		public void SubscribeCompartmentItemsEvents()
		{
			if (!subscribedCompartmentItemsEvents && this.Store != null)
			{
				subscribedCompartmentItemsEvents = true;
				this.Store.EventManagerDirectory.ElementAdded.Add(new global::System.EventHandler<DslModeling::ElementAddedEventArgs>(this.CompartmentItemAdded));
				this.Store.EventManagerDirectory.ElementDeleted.Add(new global::System.EventHandler<DslModeling::ElementDeletedEventArgs>(this.CompartmentItemDeleted));
				this.Store.EventManagerDirectory.ElementPropertyChanged.Add(new global::System.EventHandler<DslModeling::ElementPropertyChangedEventArgs>(this.CompartmentItemPropertyChanged));
				this.Store.EventManagerDirectory.RolePlayerChanged.Add(new global::System.EventHandler<DslModeling::RolePlayerChangedEventArgs>(this.CompartmentItemRolePlayerChanged));
				this.Store.EventManagerDirectory.RolePlayerOrderChanged.Add(new global::System.EventHandler<DslModeling::RolePlayerOrderChangedEventArgs>(this.CompartmentItemRolePlayerOrderChanged));
			}
		}
		
		/// <summary>
		/// Unsubscribe to events fired when compartment items changes.
		/// </summary>
		public void UnsubscribeCompartmentItemsEvents()
		{
			if (subscribedCompartmentItemsEvents)
			{
				this.Store.EventManagerDirectory.ElementAdded.Remove(new global::System.EventHandler<DslModeling::ElementAddedEventArgs>(this.CompartmentItemAdded));
				this.Store.EventManagerDirectory.ElementDeleted.Remove(new global::System.EventHandler<DslModeling::ElementDeletedEventArgs>(this.CompartmentItemDeleted));
				this.Store.EventManagerDirectory.ElementPropertyChanged.Remove(new global::System.EventHandler<DslModeling::ElementPropertyChangedEventArgs>(this.CompartmentItemPropertyChanged));
				this.Store.EventManagerDirectory.RolePlayerChanged.Remove(new global::System.EventHandler<DslModeling::RolePlayerChangedEventArgs>(this.CompartmentItemRolePlayerChanged));
				this.Store.EventManagerDirectory.RolePlayerOrderChanged.Remove(new global::System.EventHandler<DslModeling::RolePlayerOrderChangedEventArgs>(this.CompartmentItemRolePlayerOrderChanged));
				subscribedCompartmentItemsEvents = false;
			}
		}
		
		#region Event handlers
		/// <summary>
		/// Event for element added.
		/// </summary>
		private void CompartmentItemAdded(object sender, DslModeling::ElementAddedEventArgs e)
		{
			// If in Undo, Redo or Rollback the compartment item rules are not run so we must refresh the compartment list at this point if required
			bool repaintOnly = !e.ModelElement.Store.InUndoRedoOrRollback;
			CompartmentItemAddRule.ElementAdded(e, repaintOnly);
		}
		/// <summary>
		/// Event for element deleted.
		/// </summary>
		private void CompartmentItemDeleted(object sender, DslModeling::ElementDeletedEventArgs e)
		{
			bool repaintOnly = !e.ModelElement.Store.InUndoRedoOrRollback;
			CompartmentItemDeleteRule.ElementDeleted(e, repaintOnly);
		}
		/// <summary>
		/// Event for element property changed.
		/// </summary>
		private void CompartmentItemPropertyChanged(object sender, DslModeling::ElementPropertyChangedEventArgs e)
		{
			bool repaintOnly = !e.ModelElement.Store.InUndoRedoOrRollback;
			CompartmentItemChangeRule.ElementPropertyChanged(e, repaintOnly);
		}
		/// <summary>
		/// Event for role-player changed.
		/// </summary>
		private void CompartmentItemRolePlayerChanged(object sender, DslModeling::RolePlayerChangedEventArgs e)
		{
			bool repaintOnly = !e.ElementLink.Store.InUndoRedoOrRollback;
			CompartmentItemRolePlayerChangeRule.RolePlayerChanged(e, repaintOnly);
		}
		/// <summary>
		/// Event for role-player order changed.
		/// </summary>
		private void CompartmentItemRolePlayerOrderChanged(object sender, DslModeling::RolePlayerOrderChangedEventArgs e)
		{
			bool repaintOnly = !e.Link.Store.InUndoRedoOrRollback;
			CompartmentItemRolePlayerPositionChangeRule.RolePlayerPositionChanged(e, repaintOnly);
		}
		#endregion
		#endregion
		#region Shape mapping
		/// <summary>
		/// Called during view fixup to ask the parent whether a shape should be created for the given child element.
		/// </summary>
		/// <remarks>
		/// Always return true, since we assume there is only one diagram per model file for DSL scenarios.
		/// </remarks>
		protected override bool ShouldAddShapeForElement(DslModeling::ModelElement element)
		{
			return true;
		}
		
		/// <summary>
		/// Called during view fixup to configure the given child element, after it has been created.
		/// </summary>
		/// <remarks>
		/// Custom code for choosing the shapes attached to either end of a connector is called from here.
		/// </remarks>
		protected override void OnChildConfiguring(DslDiagrams::ShapeElement child, bool createdDuringViewFixup)
		{
			DslDiagrams::NodeShape sourceShape;
			DslDiagrams::NodeShape targetShape;
			DslDiagrams::BinaryLinkShape connector = child as DslDiagrams::BinaryLinkShape;
			if(connector == null)
			{
				base.OnChildConfiguring(child, createdDuringViewFixup);
				return;
			}
			this.GetSourceAndTargetForConnector(connector, out sourceShape, out targetShape);
			
			global::System.Diagnostics.Debug.Assert(sourceShape != null && targetShape != null, "Unable to find source and target shapes for connector.");
			connector.Connect(sourceShape, targetShape);
		}
		
		/// <summary>
		/// helper method to find the shapes for either end of a connector, including calling the user's custom code
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		internal void GetSourceAndTargetForConnector(DslDiagrams::BinaryLinkShape connector, out DslDiagrams::NodeShape sourceShape, out DslDiagrams::NodeShape targetShape)
		{
			sourceShape = null;
			targetShape = null;
			
			if (sourceShape == null || targetShape == null)
			{
				DslDiagrams::NodeShape[] endShapes = GetEndShapesForConnector(connector);
				if(sourceShape == null)
				{
					sourceShape = endShapes[0];
				}
				if(targetShape == null)
				{
					targetShape = endShapes[1];
				}
			}
		}
		
		/// <summary>
		/// Helper method to find shapes for either end of a connector by looking for shapes associated with either end of the relationship mapped to the connector.
		/// </summary>
		private DslDiagrams::NodeShape[] GetEndShapesForConnector(DslDiagrams::BinaryLinkShape connector)
		{
			DslModeling::ElementLink link = connector.ModelElement as DslModeling::ElementLink;
			DslDiagrams::NodeShape sourceShape = null, targetShape = null;
			if (link != null)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = link.LinkedElements;
				if (linkedElements.Count == 2)
				{
					DslDiagrams::Diagram currentDiagram = this.Diagram;
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							sourceShape = shape;
							break;
						}
					}
					
					presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							targetShape = shape;
							break;
						}
					}
		
				}
			}
			
			return new DslDiagrams::NodeShape[] { sourceShape, targetShape };
		}
		
		/// <summary>
		/// Creates a new shape for the given model element as part of view fixup
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Justification = "Generated code.")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
		protected override DslDiagrams::ShapeElement CreateChildShape(DslModeling::ModelElement element)
		{
			if(element is global::Compañía.IotDsl.ApiREST)
			{
				global::Compañía.IotDsl.ApiRESTImage newShape = new global::Compañía.IotDsl.ApiRESTImage(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Compañía.IotDsl.PhoneApp)
			{
				global::Compañía.IotDsl.PhoneAppImage newShape = new global::Compañía.IotDsl.PhoneAppImage(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Compañía.IotDsl.WebApp)
			{
				global::Compañía.IotDsl.WebAppShape newShape = new global::Compañía.IotDsl.WebAppShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Compañía.IotDsl.SQLStorage)
			{
				global::Compañía.IotDsl.SQLStorageShape newShape = new global::Compañía.IotDsl.SQLStorageShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Compañía.IotDsl.DataAnalytics)
			{
				global::Compañía.IotDsl.DataAnalyticsShape newShape = new global::Compañía.IotDsl.DataAnalyticsShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Compañía.IotDsl.IoTCenter)
			{
				global::Compañía.IotDsl.IoTCenterShape newShape = new global::Compañía.IotDsl.IoTCenterShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Compañía.IotDsl.NoSQLStorage)
			{
				global::Compañía.IotDsl.NoSQLStorageShape newShape = new global::Compañía.IotDsl.NoSQLStorageShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Compañía.IotDsl.AppService)
			{
				global::Compañía.IotDsl.AppServiceImage newShape = new global::Compañía.IotDsl.AppServiceImage(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Compañía.IotDsl.MessageService)
			{
				global::Compañía.IotDsl.MessageServiceShape newShape = new global::Compañía.IotDsl.MessageServiceShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Compañía.IotDsl.LineGraph)
			{
				global::Compañía.IotDsl.LineGrapghShape newShape = new global::Compañía.IotDsl.LineGrapghShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Compañía.IotDsl.IoTCenterHasDevices)
			{
				global::Compañía.IotDsl.DeviceToIoTCenter newShape = new global::Compañía.IotDsl.DeviceToIoTCenter(this.Partition);
				return newShape;
			}
			if(element is global::Compañía.IotDsl.DeviceReferenciasSensors)
			{
				global::Compañía.IotDsl.DeviceToSensorConnection newShape = new global::Compañía.IotDsl.DeviceToSensorConnection(this.Partition);
				return newShape;
			}
			if(element is global::Compañía.IotDsl.EndpointConnectsCloudService)
			{
				global::Compañía.IotDsl.EndpointToCloudService newShape = new global::Compañía.IotDsl.EndpointToCloudService(this.Partition);
				return newShape;
			}
			if(element is global::Compañía.IotDsl.Graph)
			{
				global::Compañía.IotDsl.GraphShape newShape = new global::Compañía.IotDsl.GraphShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Compañía.IotDsl.ResourceGroup)
			{
				global::Compañía.IotDsl.ResourceGroupShape newShape = new global::Compañía.IotDsl.ResourceGroupShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Compañía.IotDsl.Sensor)
			{
				global::Compañía.IotDsl.SensorShape newShape = new global::Compañía.IotDsl.SensorShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Compañía.IotDsl.Device)
			{
				global::Compañía.IotDsl.DeviceShape newShape = new global::Compañía.IotDsl.DeviceShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Compañía.IotDsl.Endpoint)
			{
				global::Compañía.IotDsl.EndpointPort newShape = new global::Compañía.IotDsl.EndpointPort(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Compañía.IotDsl.CloudService)
			{
				global::Compañía.IotDsl.CloudServiceShape newShape = new global::Compañía.IotDsl.CloudServiceShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Compañía.IotDsl.AppServiceReferenciasMessageService)
			{
				global::Compañía.IotDsl.AppServiceToMessageConnection newShape = new global::Compañía.IotDsl.AppServiceToMessageConnection(this.Partition);
				return newShape;
			}
			return base.CreateChildShape(element);
		}
		#endregion
		#region Decorator mapping
		/// <summary>
		/// Initialize shape decorator mappings.  This is done here rather than in individual shapes because decorator maps
		/// are defined per diagram type rather than per shape type.
		/// </summary>
		protected override void InitializeShapeFields(global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields)
		{
			base.InitializeShapeFields(shapeFields);
			global::Compañía.IotDsl.ResourceGroupShape.DecoratorsInitialized += ResourceGroupShapeDecoratorMap.OnDecoratorsInitialized;
			global::Compañía.IotDsl.AppServiceImage.DecoratorsInitialized += AppServiceImageDecoratorMap.OnDecoratorsInitialized;
			global::Compañía.IotDsl.ApiRESTImage.DecoratorsInitialized += ApiRESTImageDecoratorMap.OnDecoratorsInitialized;
			global::Compañía.IotDsl.PhoneAppImage.DecoratorsInitialized += PhoneAppImageDecoratorMap.OnDecoratorsInitialized;
			global::Compañía.IotDsl.DeviceShape.DecoratorsInitialized += DeviceShapeDecoratorMap.OnDecoratorsInitialized;
			global::Compañía.IotDsl.IoTCenterShape.DecoratorsInitialized += IoTCenterShapeDecoratorMap.OnDecoratorsInitialized;
			global::Compañía.IotDsl.SensorShape.DecoratorsInitialized += SensorShapeDecoratorMap.OnDecoratorsInitialized;
			global::Compañía.IotDsl.MessageServiceShape.DecoratorsInitialized += MessageServiceShapeDecoratorMap.OnDecoratorsInitialized;
			global::Compañía.IotDsl.DataAnalyticsShape.DecoratorsInitialized += DataAnalyticsShapeDecoratorMap.OnDecoratorsInitialized;
			global::Compañía.IotDsl.SQLStorageShape.DecoratorsInitialized += SQLStorageShapeDecoratorMap.OnDecoratorsInitialized;
			global::Compañía.IotDsl.NoSQLStorageShape.DecoratorsInitialized += NoSQLStorageShapeDecoratorMap.OnDecoratorsInitialized;
			global::Compañía.IotDsl.WebAppShape.DecoratorsInitialized += WebAppShapeDecoratorMap.OnDecoratorsInitialized;
			global::Compañía.IotDsl.DeviceToIoTCenter.DecoratorsInitialized += DeviceToIoTCenterDecoratorMap.OnDecoratorsInitialized;
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ResourceGroupShape.
		/// </summary>
		internal static partial class ResourceGroupShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ResourceGroupShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Compañía.IotDsl.ResourceGroup.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Name").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for AppServiceImage.
		/// </summary>
		internal static partial class AppServiceImageDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for AppServiceImage.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Compañía.IotDsl.CloudService.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Name").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ApiRESTImage.
		/// </summary>
		internal static partial class ApiRESTImageDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ApiRESTImage.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Compañía.IotDsl.CloudService.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Name").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for PhoneAppImage.
		/// </summary>
		internal static partial class PhoneAppImageDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for PhoneAppImage.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Compañía.IotDsl.CloudService.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Name").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for DeviceShape.
		/// </summary>
		internal static partial class DeviceShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for DeviceShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Compañía.IotDsl.Device.deviceIdDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "DeviceId").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Compañía.IotDsl.Device.OSDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "OS").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Compañía.IotDsl.Device.ProgrammingLenguageDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "ProgrammingLenguage").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Compañía.IotDsl.Device.ProtocolDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Protocol").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for IoTCenterShape.
		/// </summary>
		internal static partial class IoTCenterShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for IoTCenterShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Compañía.IotDsl.CloudService.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Name").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for SensorShape.
		/// </summary>
		internal static partial class SensorShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for SensorShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Compañía.IotDsl.Sensor.RefreshRateDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "RefreshRate").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Compañía.IotDsl.Sensor.SensorIdDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "SensorId").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MessageServiceShape.
		/// </summary>
		internal static partial class MessageServiceShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MessageServiceShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Compañía.IotDsl.CloudService.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Name").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for DataAnalyticsShape.
		/// </summary>
		internal static partial class DataAnalyticsShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for DataAnalyticsShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Compañía.IotDsl.CloudService.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Name").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for SQLStorageShape.
		/// </summary>
		internal static partial class SQLStorageShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for SQLStorageShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Compañía.IotDsl.CloudService.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Name").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Compañía.IotDsl.SQLStorage.PasswordDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Password").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Compañía.IotDsl.SQLStorage.UserDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "User").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for NoSQLStorageShape.
		/// </summary>
		internal static partial class NoSQLStorageShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for NoSQLStorageShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Compañía.IotDsl.CloudService.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Name").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for WebAppShape.
		/// </summary>
		internal static partial class WebAppShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for WebAppShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Compañía.IotDsl.CloudService.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Name").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for DeviceToIoTCenter.
		/// </summary>
		internal static partial class DeviceToIoTCenterDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for DeviceToIoTCenter.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Compañía.IotDsl.IoTCenterHasDevices.DeviceKeyDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "DeviceKey").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		#endregion
		
		#region Connect actions
		private bool changingMouseAction;
		private global::Compañía.IotDsl.EndpointtoCloudServiceConnectionConnectAction endpointtoCloudServiceConnectionConnectAction;
		private global::Compañía.IotDsl.DeviceToSensorConnectionConnectAction deviceToSensorConnectionConnectAction;
		private global::Compañía.IotDsl.IoTCenterToDeviceToolConnectAction ioTCenterToDeviceToolConnectAction;
		/// <summary>
		/// Virtual method to provide a filter when to select the mouse action
		/// </summary>
		/// <param name="activeView">Currently active view</param>
		/// <param name="filter">filter string used to filter the toolbox items</param>
		protected virtual bool SelectedToolboxItemSupportsFilterString(DslDiagrams::DiagramView activeView, string filter)
		{
			return activeView.SelectedToolboxItemSupportsFilterString(filter);
		}
		/// <summary>
		/// Override to provide the right mouse action when trying
		/// to create links on the diagram
		/// </summary>
		/// <param name="pointArgs"></param>
		public override void OnViewMouseEnter(DslDiagrams::DiagramPointEventArgs pointArgs)
		{
			if (pointArgs  == null) throw new global::System.ArgumentNullException("pointArgs");
		
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
			if(activeView != null)
			{
				DslDiagrams::MouseAction action = null;
				if (SelectedToolboxItemSupportsFilterString(activeView, global::Compañía.IotDsl.IotDslToolboxHelper.EndpointtoCloudServiceConnectionFilterString))
				{
					if (this.endpointtoCloudServiceConnectionConnectAction == null)
					{
						this.endpointtoCloudServiceConnectionConnectAction = new global::Compañía.IotDsl.EndpointtoCloudServiceConnectionConnectAction(this);
						this.endpointtoCloudServiceConnectionConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.endpointtoCloudServiceConnectionConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::Compañía.IotDsl.IotDslToolboxHelper.DeviceToSensorConnectionFilterString))
				{
					if (this.deviceToSensorConnectionConnectAction == null)
					{
						this.deviceToSensorConnectionConnectAction = new global::Compañía.IotDsl.DeviceToSensorConnectionConnectAction(this);
						this.deviceToSensorConnectionConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.deviceToSensorConnectionConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::Compañía.IotDsl.IotDslToolboxHelper.IoTCenterToDeviceToolFilterString))
				{
					if (this.ioTCenterToDeviceToolConnectAction == null)
					{
						this.ioTCenterToDeviceToolConnectAction = new global::Compañía.IotDsl.IoTCenterToDeviceToolConnectAction(this);
						this.ioTCenterToDeviceToolConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.ioTCenterToDeviceToolConnectAction;
				} 
				else
				{
					action = null;
				}
				
				if (pointArgs.DiagramClientView.ActiveMouseAction != action)
				{
					try
					{
						this.changingMouseAction = true;
						pointArgs.DiagramClientView.ActiveMouseAction = action;
					}
					finally
					{
						this.changingMouseAction = false;
					}
				}
			}
		}
		
		/// <summary>
		/// Snap toolbox selection back to regular pointer after using a custom connect action.
		/// </summary>
		private void OnConnectActionDeactivated(object sender, DslDiagrams::DiagramEventArgs e)
		{
			OnMouseActionDeactivated();
		}
		
		/// <summary>
		/// Overridable method to manage the mouse deactivation. The default implementation snap stoolbox selection back to regular pointer 
		/// after using a custom connect action.
		/// </summary>
		protected virtual void OnMouseActionDeactivated()
		{
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
		
			if (activeView != null && activeView.Toolbox != null)
			{
				// If we're not changing mouse action due to changing toolbox selection change,
				// reset toolbox selection.
				if (!this.changingMouseAction)
				{
					activeView.Toolbox.SelectedToolboxItemUsed();
				}
			}
		}
		#endregion
		
		/// <summary>
		/// Dispose of connect actions.
		/// </summary>
		protected override void Dispose(bool disposing)
		{
			try
			{
				if(disposing)
				{
					if(this.endpointtoCloudServiceConnectionConnectAction != null)
					{
						this.endpointtoCloudServiceConnectionConnectAction.Dispose();
						this.endpointtoCloudServiceConnectionConnectAction = null;
					}
					if(this.deviceToSensorConnectionConnectAction != null)
					{
						this.deviceToSensorConnectionConnectAction.Dispose();
						this.deviceToSensorConnectionConnectAction = null;
					}
					if(this.ioTCenterToDeviceToolConnectAction != null)
					{
						this.ioTCenterToDeviceToolConnectAction.Dispose();
						this.ioTCenterToDeviceToolConnectAction = null;
					}
					this.UnsubscribeCompartmentItemsEvents();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}
		#region Constructors, domain class Id
	
		/// <summary>
		/// IotDslDiagram domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x32697784, 0x6bc9, 0x41c1, 0x9b, 0x38, 0xd5, 0x06, 0xff, 0xa3, 0xb7, 0x91);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public IotDslDiagram(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public IotDslDiagram(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace Compañía.IotDsl
{
	
		/// <summary>
		/// Double derived implementation for the rule that initiates view fixup when an element that has an associated shape is added to the model.
		/// This now enables the DSL author to everride the SkipFixUp() method 
		/// </summary>
		internal partial class FixUpDiagramBase : DslModeling::AddRule
		{
			protected virtual bool SkipFixup(DslModeling::ModelElement childElement)
			{
				return childElement.IsDeleted;
			}
		}
	
		/// <summary>
		/// Rule that initiates view fixup when an element that has an associated shape is added to the model. 
		/// </summary>
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.ApiREST), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.PhoneApp), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.WebApp), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.MessageService), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.AppService), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.LineGraph), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.IoTCenter), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.DataAnalytics), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.SQLStorage), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.NoSQLStorage), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.DeviceReferenciasSensors), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.EndpointConnectsCloudService), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.Graph), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.ResourceGroup), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.Sensor), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.Device), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.Endpoint), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority + 1, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.CloudService), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.IoTCenterHasDevices), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.AppServiceReferenciasMessageService), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed partial class FixUpDiagram : FixUpDiagramBase
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
			
				DslModeling::ModelElement childElement = e.ModelElement;
				if (this.SkipFixup(childElement))
					return;
				DslModeling::ModelElement parentElement;
				if(childElement is DslModeling::ElementLink)
				{
					parentElement = GetParentForRelationship((DslModeling::ElementLink)childElement);
				} else
				if(childElement is global::Compañía.IotDsl.ApiREST)
				{
					parentElement = GetParentForApiREST((global::Compañía.IotDsl.ApiREST)childElement);
				} else
				if(childElement is global::Compañía.IotDsl.PhoneApp)
				{
					parentElement = GetParentForPhoneApp((global::Compañía.IotDsl.PhoneApp)childElement);
				} else
				if(childElement is global::Compañía.IotDsl.WebApp)
				{
					parentElement = GetParentForWebApp((global::Compañía.IotDsl.WebApp)childElement);
				} else
				if(childElement is global::Compañía.IotDsl.MessageService)
				{
					parentElement = GetParentForMessageService((global::Compañía.IotDsl.MessageService)childElement);
				} else
				if(childElement is global::Compañía.IotDsl.AppService)
				{
					parentElement = GetParentForAppService((global::Compañía.IotDsl.AppService)childElement);
				} else
				if(childElement is global::Compañía.IotDsl.LineGraph)
				{
					parentElement = GetParentForLineGraph((global::Compañía.IotDsl.LineGraph)childElement);
				} else
				if(childElement is global::Compañía.IotDsl.IoTCenter)
				{
					parentElement = GetParentForIoTCenter((global::Compañía.IotDsl.IoTCenter)childElement);
				} else
				if(childElement is global::Compañía.IotDsl.DataAnalytics)
				{
					parentElement = GetParentForDataAnalytics((global::Compañía.IotDsl.DataAnalytics)childElement);
				} else
				if(childElement is global::Compañía.IotDsl.SQLStorage)
				{
					parentElement = GetParentForSQLStorage((global::Compañía.IotDsl.SQLStorage)childElement);
				} else
				if(childElement is global::Compañía.IotDsl.NoSQLStorage)
				{
					parentElement = GetParentForNoSQLStorage((global::Compañía.IotDsl.NoSQLStorage)childElement);
				} else
				if(childElement is global::Compañía.IotDsl.Graph)
				{
					parentElement = GetParentForGraph((global::Compañía.IotDsl.Graph)childElement);
				} else
				if(childElement is global::Compañía.IotDsl.ResourceGroup)
				{
					parentElement = GetParentForResourceGroup((global::Compañía.IotDsl.ResourceGroup)childElement);
				} else
				if(childElement is global::Compañía.IotDsl.Sensor)
				{
					parentElement = GetParentForSensor((global::Compañía.IotDsl.Sensor)childElement);
				} else
				if(childElement is global::Compañía.IotDsl.Device)
				{
					parentElement = GetParentForDevice((global::Compañía.IotDsl.Device)childElement);
				} else
				if(childElement is global::Compañía.IotDsl.Endpoint)
				{
					parentElement = GetParentForEndpoint((global::Compañía.IotDsl.Endpoint)childElement);
				} else
				if(childElement is global::Compañía.IotDsl.CloudService)
				{
					parentElement = GetParentForCloudService((global::Compañía.IotDsl.CloudService)childElement);
				} else
				{
					parentElement = null;
				}
				
				if(parentElement != null)
				{
					DslDiagrams::Diagram.FixUpDiagram(parentElement, childElement);
				}
			}
			public static global::Compañía.IotDsl.IoTDsl GetParentForResourceGroup( global::Compañía.IotDsl.ResourceGroup root )
			{
				// Segments 0 and 1
				global::Compañía.IotDsl.IoTDsl result = root.IoTDsl;
				if ( result == null ) return null;
				return result;
			}
			public static global::Compañía.IotDsl.IoTDsl GetParentForAppService( global::Compañía.IotDsl.CloudService root )
			{
				// Segments 0 and 1
				global::Compañía.IotDsl.ResourceGroup root2 = root.ResourceGroup;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::Compañía.IotDsl.IoTDsl result = root2.IoTDsl;
				if ( result == null ) return null;
				return result;
			}
			public static global::Compañía.IotDsl.IoTDsl GetParentForCloudService( global::Compañía.IotDsl.CloudService root )
			{
				// Segments 0 and 1
				global::Compañía.IotDsl.ResourceGroup root2 = root.ResourceGroup;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::Compañía.IotDsl.IoTDsl result = root2.IoTDsl;
				if ( result == null ) return null;
				return result;
			}
			public static global::Compañía.IotDsl.IoTCenter GetParentForEndpoint( global::Compañía.IotDsl.Endpoint root )
			{
				// Segments 0 and 1
				global::Compañía.IotDsl.IoTCenter result = root.IoTCenter;
				if ( result == null ) return null;
				return result;
			}
			public static global::Compañía.IotDsl.IoTDsl GetParentForApiREST( global::Compañía.IotDsl.CloudService root )
			{
				// Segments 0 and 1
				global::Compañía.IotDsl.ResourceGroup root2 = root.ResourceGroup;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::Compañía.IotDsl.IoTDsl result = root2.IoTDsl;
				if ( result == null ) return null;
				return result;
			}
			public static global::Compañía.IotDsl.IoTDsl GetParentForPhoneApp( global::Compañía.IotDsl.CloudService root )
			{
				// Segments 0 and 1
				global::Compañía.IotDsl.ResourceGroup root2 = root.ResourceGroup;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::Compañía.IotDsl.IoTDsl result = root2.IoTDsl;
				if ( result == null ) return null;
				return result;
			}
			public static global::Compañía.IotDsl.IoTDsl GetParentForDevice( global::Compañía.IotDsl.Device root )
			{
				// Segments 0 and 1
				global::Compañía.IotDsl.IoTDsl result = root.IoTDsl;
				if ( result == null ) return null;
				return result;
			}
			public static global::Compañía.IotDsl.IoTDsl GetParentForIoTCenter( global::Compañía.IotDsl.CloudService root )
			{
				// Segments 0 and 1
				global::Compañía.IotDsl.ResourceGroup root2 = root.ResourceGroup;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::Compañía.IotDsl.IoTDsl result = root2.IoTDsl;
				if ( result == null ) return null;
				return result;
			}
			public static global::Compañía.IotDsl.IoTDsl GetParentForSensor( global::Compañía.IotDsl.Sensor root )
			{
				// Segments 0 and 1
				global::Compañía.IotDsl.IoTDsl result = root.IoTDsl;
				if ( result == null ) return null;
				return result;
			}
			public static global::Compañía.IotDsl.IoTDsl GetParentForMessageService( global::Compañía.IotDsl.CloudService root )
			{
				// Segments 0 and 1
				global::Compañía.IotDsl.ResourceGroup root2 = root.ResourceGroup;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::Compañía.IotDsl.IoTDsl result = root2.IoTDsl;
				if ( result == null ) return null;
				return result;
			}
			public static global::Compañía.IotDsl.IoTDsl GetParentForDataAnalytics( global::Compañía.IotDsl.CloudService root )
			{
				// Segments 0 and 1
				global::Compañía.IotDsl.ResourceGroup root2 = root.ResourceGroup;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::Compañía.IotDsl.IoTDsl result = root2.IoTDsl;
				if ( result == null ) return null;
				return result;
			}
			public static global::Compañía.IotDsl.IoTDsl GetParentForSQLStorage( global::Compañía.IotDsl.CloudService root )
			{
				// Segments 0 and 1
				global::Compañía.IotDsl.ResourceGroup root2 = root.ResourceGroup;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::Compañía.IotDsl.IoTDsl result = root2.IoTDsl;
				if ( result == null ) return null;
				return result;
			}
			public static global::Compañía.IotDsl.IoTDsl GetParentForNoSQLStorage( global::Compañía.IotDsl.CloudService root )
			{
				// Segments 0 and 1
				global::Compañía.IotDsl.ResourceGroup root2 = root.ResourceGroup;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::Compañía.IotDsl.IoTDsl result = root2.IoTDsl;
				if ( result == null ) return null;
				return result;
			}
			public static global::Compañía.IotDsl.IoTDsl GetParentForWebApp( global::Compañía.IotDsl.CloudService root )
			{
				// Segments 0 and 1
				global::Compañía.IotDsl.ResourceGroup root2 = root.ResourceGroup;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::Compañía.IotDsl.IoTDsl result = root2.IoTDsl;
				if ( result == null ) return null;
				return result;
			}
			public static global::Compañía.IotDsl.IoTDsl GetParentForGraph( global::Compañía.IotDsl.Graph root )
			{
				// Segments 0 and 1
				global::Compañía.IotDsl.CloudService root2 = root.AppService as global::Compañía.IotDsl.CloudService;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::Compañía.IotDsl.ResourceGroup root4 = root2.ResourceGroup;
				if ( root4 == null ) return null;
				// Segments 4 and 5
				global::Compañía.IotDsl.IoTDsl result = root4.IoTDsl;
				if ( result == null ) return null;
				return result;
			}
			public static global::Compañía.IotDsl.IoTDsl GetParentForLineGraph( global::Compañía.IotDsl.Graph root )
			{
				// Segments 0 and 1
				global::Compañía.IotDsl.CloudService root2 = root.AppService as global::Compañía.IotDsl.CloudService;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::Compañía.IotDsl.ResourceGroup root4 = root2.ResourceGroup;
				if ( root4 == null ) return null;
				// Segments 4 and 5
				global::Compañía.IotDsl.IoTDsl result = root4.IoTDsl;
				if ( result == null ) return null;
				return result;
			}
			private static DslModeling::ModelElement GetParentForRelationship(DslModeling::ElementLink elementLink)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = elementLink.LinkedElements;
	
				if (linkedElements.Count == 2)
				{
					DslDiagrams::ShapeElement sourceShape = linkedElements[0] as DslDiagrams::ShapeElement;
					DslDiagrams::ShapeElement targetShape = linkedElements[1] as DslDiagrams::ShapeElement;
	
					if(sourceShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								sourceShape = shape;
								break;
							}
						}
					}
					
					if(targetShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								targetShape = shape;
								break;
							}
						}
					}
					
					if(sourceShape == null || targetShape == null)
					{
						global::System.Diagnostics.Debug.Fail("Unable to find source and/or target shape for view fixup.");
						return null;
					}
	
					DslDiagrams::ShapeElement sourceParent = sourceShape.ParentShape;
					DslDiagrams::ShapeElement targetParent = targetShape.ParentShape;
	
					while (sourceParent != targetParent && sourceParent != null)
					{
						DslDiagrams::ShapeElement curParent = targetParent;
						while (sourceParent != curParent && curParent != null)
						{
							curParent = curParent.ParentShape;
						}
	
						if(sourceParent == curParent)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					while (sourceParent != null)
					{
						// ensure that the parent can parent connectors (i.e., a diagram or a swimlane).
						if(sourceParent is DslDiagrams::Diagram || sourceParent is DslDiagrams::SwimlaneShape)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					global::System.Diagnostics.Debug.Assert(sourceParent != null && sourceParent.ModelElement != null, "Unable to find common parent for view fixup.");
					return sourceParent.ModelElement;
				}
	
				return null;
			}
		}
		
		/// <summary>
		/// Rule to update compartments when an item is added to the list
		/// </summary>
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.GraphHasVariables), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemAddRule : DslModeling::AddRule
		{
			/// <summary>
			/// Called when an element is added. 
			/// </summary>
			/// <param name="e"></param>
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				ElementAdded(e, false);
			}
	
			internal static void ElementAdded(DslModeling::ElementAddedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if (e.ModelElement.IsDeleted)
					return;
				if(e.ModelElement is global::Compañía.IotDsl.GraphHasVariables)
				{
					global::System.Collections.IEnumerable elements = GetGraphForGraphShapeVariablesFromLastLink((global::Compañía.IotDsl.GraphHasVariables)e.ModelElement);
					UpdateCompartments(elements, typeof(global::Compañía.IotDsl.GraphShape), "Variables", repaintOnly);
				}
			}
			
			#region static DomainPath traversal methods to get the list of compartments to update
			internal static global::System.Collections.ICollection GetGraphForGraphShapeVariablesFromLastLink(global::Compañía.IotDsl.GraphHasVariables root)
			{
				// Segment 0
				global::Compañía.IotDsl.Graph result = root.Graph;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetGraphForGraphShapeVariables(global::Compañía.IotDsl.Variable root)
			{
				// Segments 1 and 0
				global::Compañía.IotDsl.Graph result = root.Graph;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			#endregion
	
			#region helper method to update compartments 
			/// <summary>
			/// Updates the compartments for the shapes associated to the given list of model elements
			/// </summary>
			/// <param name="elements">List of model elements</param>
			/// <param name="shapeType">The type of shape that needs updating</param>
			/// <param name="compartmentName">The name of the compartment to update</param>
			/// <param name="repaintOnly">If true, the method will only invalidate the shape for a repaint, without re-initializing the shape.</param>
			internal static void UpdateCompartments(global::System.Collections.IEnumerable elements, global::System.Type shapeType, string compartmentName, bool repaintOnly)
			{
				foreach (DslModeling::ModelElement element in elements)
				{
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
					foreach (DslDiagrams::PresentationElement pel in pels)
					{
						DslDiagrams::CompartmentShape compartmentShape = pel as DslDiagrams::CompartmentShape;
						if (compartmentShape != null && shapeType.IsAssignableFrom(compartmentShape.GetType()))
						{
							if (repaintOnly)
							{
								compartmentShape.Invalidate();
							}
							else
							{
								foreach(DslDiagrams::CompartmentMapping mapping in compartmentShape.GetCompartmentMappings())
								{
									if(mapping.CompartmentId==compartmentName)
									{
										mapping.InitializeCompartmentShape(compartmentShape);
										break;
									}
								}
							}
						}
					}
				}
			}
			#endregion
		}
		
		/// <summary>
		/// Rule to update compartments when an items is removed from the list
		/// </summary>
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.GraphHasVariables), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemDeleteRule : DslModeling::DeleteRule
		{
			/// <summary>
			/// Called when an element is deleted
			/// </summary>
			/// <param name="e"></param>
			public override void ElementDeleted(DslModeling::ElementDeletedEventArgs e)
			{
				ElementDeleted(e, false);
			}
			
			internal static void ElementDeleted(DslModeling::ElementDeletedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(e.ModelElement is global::Compañía.IotDsl.GraphHasVariables)
				{
					global::System.Collections.ICollection elements = CompartmentItemAddRule.GetGraphForGraphShapeVariablesFromLastLink((global::Compañía.IotDsl.GraphHasVariables)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Compañía.IotDsl.GraphShape), "Variables", repaintOnly);
				}
			}
		}
		
		/// <summary>
		/// Rule to update compartments when the property on an item being displayed changes.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.Variable), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemChangeRule : DslModeling::ChangeRule 
		{
			/// <summary>
			/// Called when an element is changed
			/// </summary>
			/// <param name="e"></param>
			public override void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e)
			{
				ElementPropertyChanged(e, false);
			}
			
			internal static void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(e.ModelElement is global::Compañía.IotDsl.Variable && e.DomainProperty.Id == global::Compañía.IotDsl.Variable.TypeDomainPropertyId)
				{
					global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetGraphForGraphShapeVariables((global::Compañía.IotDsl.Variable)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Compañía.IotDsl.GraphShape), "Variables", repaintOnly);
				}
			}
		}
		
		/// <summary>
		/// Rule to update compartments when a roleplayer change happens
		/// </summary>
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.GraphHasVariables), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemRolePlayerChangeRule : DslModeling::RolePlayerChangeRule 
		{
			/// <summary>
			/// Called when the roleplayer on a link changes.
			/// </summary>
			/// <param name="e"></param>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				RolePlayerChanged(e, false);
			}
			
			internal static void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(typeof(global::Compañía.IotDsl.GraphHasVariables).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(e.DomainRole.IsSource)
					{
						//global::System.Collections.IEnumerable oldElements = CompartmentItemAddRule.GetGraphForGraphShapeVariablesFromLastLink((global::Compañía.IotDsl.Variable)e.OldRolePlayer);
						//foreach(DslModeling::ModelElement element in oldElements)
						//{
						//	DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
						//	foreach(DslDiagrams::PresentationElement pel in pels)
						//	{
						//		global::Compañía.IotDsl.GraphShape compartmentShape = pel as global::Compañía.IotDsl.GraphShape;
						//		if(compartmentShape != null)
						//		{
						//			compartmentShape.GetCompartmentMappings()[0].InitializeCompartmentShape(compartmentShape);
						//		}
						//	}
						//}
						
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetGraphForGraphShapeVariablesFromLastLink((global::Compañía.IotDsl.GraphHasVariables)e.ElementLink);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Compañía.IotDsl.GraphShape), "Variables", repaintOnly);
					}
					else 
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetGraphForGraphShapeVariables((global::Compañía.IotDsl.Variable)e.NewRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Compañía.IotDsl.GraphShape), "Variables", repaintOnly);
					}
				}
			}
		}
	
		/// <summary>
		/// Rule to update compartments when the order of items in the list changes.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.GraphHasVariables), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemRolePlayerPositionChangeRule : DslModeling::RolePlayerPositionChangeRule 
		{
			/// <summary>
			/// Called when the order of a roleplayer in a relationship changes
			/// </summary>
			/// <param name="e"></param>
			public override void RolePlayerPositionChanged(DslModeling::RolePlayerOrderChangedEventArgs e)
			{
				RolePlayerPositionChanged(e, false);
			}
			
			internal static void RolePlayerPositionChanged(DslModeling::RolePlayerOrderChangedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(typeof(global::Compañía.IotDsl.GraphHasVariables).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(!e.CounterpartDomainRole.IsSource)
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetGraphForGraphShapeVariables((global::Compañía.IotDsl.Variable)e.CounterpartRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::Compañía.IotDsl.GraphShape), "Variables", repaintOnly);
					}
				}
			}
		}
	
		/// <summary>
		/// A rule which fires when data mapped to outer text decorators has changed,
		/// so we can update the decorator host's bounds.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.CloudService), InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.IoTCenterHasDevices), InitiallyDisabled=true)]
		internal sealed class DecoratorPropertyChanged : DslModeling::ChangeRule
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Justification = "Generated code.")]
			public override void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
				
				if (e.DomainProperty.Id == global::Compañía.IotDsl.CloudService.NameDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::Compañía.IotDsl.AppServiceImage.FindAppServiceImageDecorator("Name");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::Compañía.IotDsl.AppService.DomainClassId);
					}
					decorator = global::Compañía.IotDsl.ApiRESTImage.FindApiRESTImageDecorator("Name");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::Compañía.IotDsl.ApiREST.DomainClassId);
					}
					decorator = global::Compañía.IotDsl.PhoneAppImage.FindPhoneAppImageDecorator("Name");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::Compañía.IotDsl.PhoneApp.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::Compañía.IotDsl.IoTCenterHasDevices.DeviceKeyDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::Compañía.IotDsl.DeviceToIoTCenter.FindDeviceToIoTCenterDecorator("DeviceKey");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::Compañía.IotDsl.IoTCenterHasDevices.DomainClassId);
					}
				}
			}
		}
	
		/// <summary>
		/// Reroute a connector when the role players of its underlying relationship change
		/// </summary>
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.EndpointConnectsCloudService), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.DeviceReferenciasSensors), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.IoTCenterHasDevices), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Compañía.IotDsl.AppServiceReferenciasMessageService), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed class ConnectorRolePlayerChanged : DslModeling::RolePlayerChangeRule
		{
			/// <summary>
			/// Reroute a connector when the role players of its underlying relationship change
			/// </summary>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				if (e == null) throw new global::System.ArgumentNullException("e");
	
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslDiagrams::PresentationViewsSubject> connectorLinks = DslDiagrams::PresentationViewsSubject.GetLinksToPresentation(e.ElementLink);
				foreach (DslDiagrams::PresentationViewsSubject connectorLink in connectorLinks)
				{
					// Fix up any binary link shapes attached to the element link.
					DslDiagrams::BinaryLinkShape linkShape = connectorLink.Presentation as DslDiagrams::BinaryLinkShape;
					if (linkShape != null)
					{
						global::Compañía.IotDsl.IotDslDiagram diagram = linkShape.Diagram as global::Compañía.IotDsl.IotDslDiagram;
						if (diagram != null)
						{
							if (e.NewRolePlayer != null)
							{
								DslDiagrams::NodeShape fromShape;
								DslDiagrams::NodeShape toShape;
								diagram.GetSourceAndTargetForConnector(linkShape, out fromShape, out toShape);
								if (fromShape != null && toShape != null)
								{
									if (!object.Equals(fromShape, linkShape.FromShape))
									{
										linkShape.FromShape = fromShape;
									}
									if (!object.Equals(linkShape.ToShape, toShape))
									{
										linkShape.ToShape = toShape;
									}
								}
								else
								{
									// delete the connector if we cannot find an appropriate target shape.
									linkShape.Delete();
								}
							}
							else
							{
								// delete the connector if the new role player is null.
								linkShape.Delete();
							}
						}
					}
				}
			}
		}
	}
