//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace Compañía.IotDsl
{
	/// <summary>
	/// DomainModel IotDslDomainModel
	/// Description for Compañía.IotDsl.IotDsl
	/// </summary>
	[DslDesign::DisplayNameResource("Compañía.IotDsl.IotDslDomainModel.DisplayName", typeof(global::Compañía.IotDsl.IotDslDomainModel), "Compañía.IotDsl.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Compañía.IotDsl.IotDslDomainModel.Description", typeof(global::Compañía.IotDsl.IotDslDomainModel), "Compañía.IotDsl.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("6cefa6ae-2700-42e9-9ae8-a85721e9161b")]
	public partial class IotDslDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// IotDslDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0x6cefa6ae, 0x2700, 0x42e9, 0x9a, 0xe8, 0xa8, 0x57, 0x21, 0xe9, 0x16, 0x1b);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public IotDslDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(IotDsl1),
				typeof(GrupoDeRecursos),
				typeof(CentroIoT),
				typeof(MessagingasaService),
				typeof(DataAnalytics),
				typeof(AlmacenamientoNoSQL),
				typeof(VisualizaconDatos),
				typeof(IotDsl1TieneGrupoDeRecursos),
				typeof(GrupoDeRecursosTieneCentroIoT),
				typeof(GrupoDeRecursosTieneMessagingasaService),
				typeof(CentroIoTReferenciasMessagingasaService),
				typeof(GrupoDeRecursosTieneDataAnalytics),
				typeof(EntradaIotHub),
				typeof(GrupoDeRecursosTieneAlmacenamientoNoSQL),
				typeof(SalidaAlmacenamientoNoSQL),
				typeof(GrupoDeRecursosTieneVisualizaconDatos),
				typeof(MessagingasaServiceReferenciasVisualizaconDatos),
				typeof(IotDslDiagram),
				typeof(ConexionIotHubMAAS),
				typeof(EntradaIoTDataAnalytics),
				typeof(SalidaNoSQLDataAnalytics),
				typeof(ConexionMAASVisualizacion),
				typeof(GrupoDeRecursosShape),
				typeof(CentroIoTImage),
				typeof(MAASImage),
				typeof(DataAnalyticsImage),
				typeof(AlamcenamientoNoSQLImage),
				typeof(VisualizacionImagen),
				typeof(global::Compañía.IotDsl.FixUpDiagram),
				typeof(global::Compañía.IotDsl.DecoratorPropertyChanged),
				typeof(global::Compañía.IotDsl.ConnectorRolePlayerChanged),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(GrupoDeRecursos), "Nombre", GrupoDeRecursos.NombreDomainPropertyId, typeof(GrupoDeRecursos.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(GrupoDeRecursos), "Location", GrupoDeRecursos.LocationDomainPropertyId, typeof(GrupoDeRecursos.LocationPropertyHandler)),
				new DomainMemberInfo(typeof(CentroIoT), "Nombre", CentroIoT.NombreDomainPropertyId, typeof(CentroIoT.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(MessagingasaService), "Nombre", MessagingasaService.NombreDomainPropertyId, typeof(MessagingasaService.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(DataAnalytics), "Nombre", DataAnalytics.NombreDomainPropertyId, typeof(DataAnalytics.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(AlmacenamientoNoSQL), "Nombre", AlmacenamientoNoSQL.NombreDomainPropertyId, typeof(AlmacenamientoNoSQL.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(VisualizaconDatos), "Nombre", VisualizaconDatos.NombreDomainPropertyId, typeof(VisualizaconDatos.NombrePropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(IotDsl1TieneGrupoDeRecursos), "IotDsl1", IotDsl1TieneGrupoDeRecursos.IotDsl1DomainRoleId),
				new DomainRolePlayerInfo(typeof(IotDsl1TieneGrupoDeRecursos), "GrupoDeRecursos", IotDsl1TieneGrupoDeRecursos.GrupoDeRecursosDomainRoleId),
				new DomainRolePlayerInfo(typeof(GrupoDeRecursosTieneCentroIoT), "GrupoDeRecursos", GrupoDeRecursosTieneCentroIoT.GrupoDeRecursosDomainRoleId),
				new DomainRolePlayerInfo(typeof(GrupoDeRecursosTieneCentroIoT), "CentroIoT", GrupoDeRecursosTieneCentroIoT.CentroIoTDomainRoleId),
				new DomainRolePlayerInfo(typeof(GrupoDeRecursosTieneMessagingasaService), "GrupoDeRecursos", GrupoDeRecursosTieneMessagingasaService.GrupoDeRecursosDomainRoleId),
				new DomainRolePlayerInfo(typeof(GrupoDeRecursosTieneMessagingasaService), "MessagingasaService", GrupoDeRecursosTieneMessagingasaService.MessagingasaServiceDomainRoleId),
				new DomainRolePlayerInfo(typeof(CentroIoTReferenciasMessagingasaService), "CentroIoT", CentroIoTReferenciasMessagingasaService.CentroIoTDomainRoleId),
				new DomainRolePlayerInfo(typeof(CentroIoTReferenciasMessagingasaService), "MessagingasaService", CentroIoTReferenciasMessagingasaService.MessagingasaServiceDomainRoleId),
				new DomainRolePlayerInfo(typeof(GrupoDeRecursosTieneDataAnalytics), "GrupoDeRecursos", GrupoDeRecursosTieneDataAnalytics.GrupoDeRecursosDomainRoleId),
				new DomainRolePlayerInfo(typeof(GrupoDeRecursosTieneDataAnalytics), "DataAnalytics", GrupoDeRecursosTieneDataAnalytics.DataAnalyticsDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntradaIotHub), "DataAnalytics", EntradaIotHub.DataAnalyticsDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntradaIotHub), "CentroIoT", EntradaIotHub.CentroIoTDomainRoleId),
				new DomainRolePlayerInfo(typeof(GrupoDeRecursosTieneAlmacenamientoNoSQL), "GrupoDeRecursos", GrupoDeRecursosTieneAlmacenamientoNoSQL.GrupoDeRecursosDomainRoleId),
				new DomainRolePlayerInfo(typeof(GrupoDeRecursosTieneAlmacenamientoNoSQL), "AlmacenamientoNoSQL", GrupoDeRecursosTieneAlmacenamientoNoSQL.AlmacenamientoNoSQLDomainRoleId),
				new DomainRolePlayerInfo(typeof(SalidaAlmacenamientoNoSQL), "DataAnalytics", SalidaAlmacenamientoNoSQL.DataAnalyticsDomainRoleId),
				new DomainRolePlayerInfo(typeof(SalidaAlmacenamientoNoSQL), "AlmacenamientoNoSQL", SalidaAlmacenamientoNoSQL.AlmacenamientoNoSQLDomainRoleId),
				new DomainRolePlayerInfo(typeof(GrupoDeRecursosTieneVisualizaconDatos), "GrupoDeRecursos", GrupoDeRecursosTieneVisualizaconDatos.GrupoDeRecursosDomainRoleId),
				new DomainRolePlayerInfo(typeof(GrupoDeRecursosTieneVisualizaconDatos), "VisualizaconDatos", GrupoDeRecursosTieneVisualizaconDatos.VisualizaconDatosDomainRoleId),
				new DomainRolePlayerInfo(typeof(MessagingasaServiceReferenciasVisualizaconDatos), "MessagingasaService", MessagingasaServiceReferenciasVisualizaconDatos.MessagingasaServiceDomainRoleId),
				new DomainRolePlayerInfo(typeof(MessagingasaServiceReferenciasVisualizaconDatos), "VisualizaconDatos", MessagingasaServiceReferenciasVisualizaconDatos.VisualizaconDatosDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(18);
				createElementMap.Add(typeof(IotDsl1), 0);
				createElementMap.Add(typeof(GrupoDeRecursos), 1);
				createElementMap.Add(typeof(CentroIoT), 2);
				createElementMap.Add(typeof(MessagingasaService), 3);
				createElementMap.Add(typeof(DataAnalytics), 4);
				createElementMap.Add(typeof(AlmacenamientoNoSQL), 5);
				createElementMap.Add(typeof(VisualizaconDatos), 6);
				createElementMap.Add(typeof(IotDslDiagram), 7);
				createElementMap.Add(typeof(ConexionIotHubMAAS), 8);
				createElementMap.Add(typeof(EntradaIoTDataAnalytics), 9);
				createElementMap.Add(typeof(SalidaNoSQLDataAnalytics), 10);
				createElementMap.Add(typeof(ConexionMAASVisualizacion), 11);
				createElementMap.Add(typeof(GrupoDeRecursosShape), 12);
				createElementMap.Add(typeof(CentroIoTImage), 13);
				createElementMap.Add(typeof(MAASImage), 14);
				createElementMap.Add(typeof(DataAnalyticsImage), 15);
				createElementMap.Add(typeof(AlamcenamientoNoSQLImage), 16);
				createElementMap.Add(typeof(VisualizacionImagen), 17);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::Compañía.IotDsl.IotDslDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new IotDsl1(partition, propertyAssignments);
				case 1: return new GrupoDeRecursos(partition, propertyAssignments);
				case 2: return new CentroIoT(partition, propertyAssignments);
				case 3: return new MessagingasaService(partition, propertyAssignments);
				case 4: return new DataAnalytics(partition, propertyAssignments);
				case 5: return new AlmacenamientoNoSQL(partition, propertyAssignments);
				case 6: return new VisualizaconDatos(partition, propertyAssignments);
				case 7: return new IotDslDiagram(partition, propertyAssignments);
				case 8: return new ConexionIotHubMAAS(partition, propertyAssignments);
				case 9: return new EntradaIoTDataAnalytics(partition, propertyAssignments);
				case 10: return new SalidaNoSQLDataAnalytics(partition, propertyAssignments);
				case 11: return new ConexionMAASVisualizacion(partition, propertyAssignments);
				case 12: return new GrupoDeRecursosShape(partition, propertyAssignments);
				case 13: return new CentroIoTImage(partition, propertyAssignments);
				case 14: return new MAASImage(partition, propertyAssignments);
				case 15: return new DataAnalyticsImage(partition, propertyAssignments);
				case 16: return new AlamcenamientoNoSQLImage(partition, propertyAssignments);
				case 17: return new VisualizacionImagen(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(10);
				createElementLinkMap.Add(typeof(IotDsl1TieneGrupoDeRecursos), 0);
				createElementLinkMap.Add(typeof(GrupoDeRecursosTieneCentroIoT), 1);
				createElementLinkMap.Add(typeof(GrupoDeRecursosTieneMessagingasaService), 2);
				createElementLinkMap.Add(typeof(CentroIoTReferenciasMessagingasaService), 3);
				createElementLinkMap.Add(typeof(GrupoDeRecursosTieneDataAnalytics), 4);
				createElementLinkMap.Add(typeof(EntradaIotHub), 5);
				createElementLinkMap.Add(typeof(GrupoDeRecursosTieneAlmacenamientoNoSQL), 6);
				createElementLinkMap.Add(typeof(SalidaAlmacenamientoNoSQL), 7);
				createElementLinkMap.Add(typeof(GrupoDeRecursosTieneVisualizaconDatos), 8);
				createElementLinkMap.Add(typeof(MessagingasaServiceReferenciasVisualizaconDatos), 9);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::Compañía.IotDsl.IotDslDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new IotDsl1TieneGrupoDeRecursos(partition, roleAssignments, propertyAssignments);
				case 1: return new GrupoDeRecursosTieneCentroIoT(partition, roleAssignments, propertyAssignments);
				case 2: return new GrupoDeRecursosTieneMessagingasaService(partition, roleAssignments, propertyAssignments);
				case 3: return new CentroIoTReferenciasMessagingasaService(partition, roleAssignments, propertyAssignments);
				case 4: return new GrupoDeRecursosTieneDataAnalytics(partition, roleAssignments, propertyAssignments);
				case 5: return new EntradaIotHub(partition, roleAssignments, propertyAssignments);
				case 6: return new GrupoDeRecursosTieneAlmacenamientoNoSQL(partition, roleAssignments, propertyAssignments);
				case 7: return new SalidaAlmacenamientoNoSQL(partition, roleAssignments, propertyAssignments);
				case 8: return new GrupoDeRecursosTieneVisualizaconDatos(partition, roleAssignments, propertyAssignments);
				case 9: return new MessagingasaServiceReferenciasVisualizaconDatos(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "Compañía.IotDsl.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return IotDslDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (IotDslDomainModel.resourceManager == null)
				{
					IotDslDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(IotDslDomainModel).Assembly);
				}
				return IotDslDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return IotDslDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return IotDslDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (IotDslDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new IotDslCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					IotDslDomainModel.copyClosure = copyFilter;
				}
				return IotDslDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (IotDslDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new IotDslDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					IotDslDomainModel.removeClosure = removeFilter;
				}
				return IotDslDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::Compañía.IotDsl.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::Compañía.IotDsl.DecoratorPropertyChanged));
			ruleManager.EnableRule(typeof(global::Compañía.IotDsl.ConnectorRolePlayerChanged));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::Compañía.IotDsl.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::Compañía.IotDsl.DecoratorPropertyChanged));
			ruleManager.DisableRule(typeof(global::Compañía.IotDsl.ConnectorRolePlayerChanged));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class IotDslDeleteClosure : IotDslDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public IotDslDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class IotDslDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public IotDslDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::Compañía.IotDsl.IotDsl1TieneGrupoDeRecursos.GrupoDeRecursosDomainRoleId, true);
			DomainRoles.Add(global::Compañía.IotDsl.GrupoDeRecursosTieneCentroIoT.CentroIoTDomainRoleId, true);
			DomainRoles.Add(global::Compañía.IotDsl.GrupoDeRecursosTieneMessagingasaService.MessagingasaServiceDomainRoleId, true);
			DomainRoles.Add(global::Compañía.IotDsl.GrupoDeRecursosTieneDataAnalytics.DataAnalyticsDomainRoleId, true);
			DomainRoles.Add(global::Compañía.IotDsl.GrupoDeRecursosTieneAlmacenamientoNoSQL.AlmacenamientoNoSQLDomainRoleId, true);
			DomainRoles.Add(global::Compañía.IotDsl.GrupoDeRecursosTieneVisualizaconDatos.VisualizaconDatosDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class IotDslCopyClosure : IotDslCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public IotDslCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class IotDslCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public IotDslCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}
namespace Compañía.IotDsl
{
	/// <summary>
	/// DomainEnumeration: Location
	/// Descripción de Compañía.IotDsl.Location
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum Location
	{
		/// <summary>
		/// westeurope
		/// Descripción de Compañía.IotDsl.Location.westeurope
		/// </summary>
		[DslDesign::DescriptionResource("Compañía.IotDsl.Location/westeurope.Description", typeof(global::Compañía.IotDsl.IotDslDomainModel), "Compañía.IotDsl.GeneratedCode.DomainModelResx")]
		westeurope,
	}
}

