//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using VSShellInterop = global::Microsoft.VisualStudio.Shell.Interop;
using VSShell = global::Microsoft.VisualStudio.Shell;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslModeling = global::Microsoft.VisualStudio.Modeling;
using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Linq;
using System.Windows.Forms;
	
namespace Compañía.IotDsl
{
	/// <summary>
	/// This class implements the VS package that integrates this DSL into Visual Studio.
	/// </summary>
	[VSShell::DefaultRegistryRoot("Software\\Microsoft\\VisualStudio\\15.0")]
	[VSShell::PackageRegistration(RegisterUsing = VSShell::RegistrationMethod.Assembly, UseManagedResourcesOnly = true)]
	[VSShell::ProvideToolWindow(typeof(IotDslExplorerToolWindow), MultiInstances = false, Style = VSShell::VsDockStyle.Tabbed, Orientation = VSShell::ToolWindowOrientation.Right, Window = "{3AE79031-E1BC-11D0-8F78-00A0C9110057}")]
	[VSShell::ProvideToolWindowVisibility(typeof(IotDslExplorerToolWindow), Constants.IotDslEditorFactoryId)]
	[VSShell::ProvideStaticToolboxGroup("@CloudToolboxTab;Compañía.IotDsl.Dsl.dll", "Compañía.IotDsl.CloudToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("Compañía.IotDsl.CloudToolboxTab",
					"@ResourceGroupToolToolboxItem;Compañía.IotDsl.Dsl.dll", 
					"Compañía.IotDsl.ResourceGroupToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ResourceGroupTool", 
					"@ResourceGroupToolToolboxBitmap;Compañía.IotDsl.Dsl.dll", 
					0xff00ff,
					Index = 0)]
	[VSShell::ProvideStaticToolboxItem("Compañía.IotDsl.CloudToolboxTab",
					"@IoTCenterToolToolboxItem;Compañía.IotDsl.Dsl.dll", 
					"Compañía.IotDsl.IoTCenterToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"IoTCenterTool", 
					"@IoTCenterToolToolboxBitmap;Compañía.IotDsl.Dsl.dll", 
					0xff00ff,
					Index = 1)]
	[VSShell::ProvideStaticToolboxItem("Compañía.IotDsl.CloudToolboxTab",
					"@DataAnalyticsToolToolboxItem;Compañía.IotDsl.Dsl.dll", 
					"Compañía.IotDsl.DataAnalyticsToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"DataAnalyticsTool", 
					"@DataAnalyticsToolToolboxBitmap;Compañía.IotDsl.Dsl.dll", 
					0xff00ff,
					Index = 2)]
	[VSShell::ProvideStaticToolboxItem("Compañía.IotDsl.CloudToolboxTab",
					"@NoSQLStorageToolToolboxItem;Compañía.IotDsl.Dsl.dll", 
					"Compañía.IotDsl.NoSQLStorageToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"NoSQLStorageTool", 
					"@NoSQLStorageToolToolboxBitmap;Compañía.IotDsl.Dsl.dll", 
					0xff00ff,
					Index = 3)]
	[VSShell::ProvideStaticToolboxItem("Compañía.IotDsl.CloudToolboxTab",
					"@AppServiceToolToolboxItem;Compañía.IotDsl.Dsl.dll", 
					"Compañía.IotDsl.AppServiceToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"AppServiceTool", 
					"@AppServiceToolToolboxBitmap;Compañía.IotDsl.Dsl.dll", 
					0xff00ff,
					Index = 4)]
	[VSShell::ProvideStaticToolboxItem("Compañía.IotDsl.CloudToolboxTab",
					"@EndpointToolToolboxItem;Compañía.IotDsl.Dsl.dll", 
					"Compañía.IotDsl.EndpointToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"EndpointTool", 
					"@EndpointToolToolboxBitmap;Compañía.IotDsl.Dsl.dll", 
					0xff00ff,
					Index = 5)]
	[VSShell::ProvideStaticToolboxItem("Compañía.IotDsl.CloudToolboxTab",
					"@IotCenterEndpointConectionToolboxItem;Compañía.IotDsl.Dsl.dll", 
					"Compañía.IotDsl.IotCenterEndpointConectionToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"IotCenterEndpointConection", 
					"@IotCenterEndpointConectionToolboxBitmap;Compañía.IotDsl.Dsl.dll", 
					0xff00ff,
					Index = 6)]
	[VSShell::ProvideStaticToolboxItem("Compañía.IotDsl.CloudToolboxTab",
					"@SQLStorageToolToolboxItem;Compañía.IotDsl.Dsl.dll", 
					"Compañía.IotDsl.SQLStorageToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"SQLStorageTool", 
					"@SQLStorageToolToolboxBitmap;Compañía.IotDsl.Dsl.dll", 
					0xff00ff,
					Index = 7)]
	[VSShell::ProvideStaticToolboxItem("Compañía.IotDsl.CloudToolboxTab",
					"@EndpointtoCloudServiceConnectionToolboxItem;Compañía.IotDsl.Dsl.dll", 
					"Compañía.IotDsl.EndpointtoCloudServiceConnectionToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"EndpointtoCloudServiceConnection", 
					"@EndpointtoCloudServiceConnectionToolboxBitmap;Compañía.IotDsl.Dsl.dll", 
					0xff00ff,
					Index = 8)]
	[VSShell::ProvideStaticToolboxGroup("@DeviceToolboxTab;Compañía.IotDsl.Dsl.dll", "Compañía.IotDsl.DeviceToolboxTab")]
	[VSShell::ProvideEditorFactory(typeof(IotDslEditorFactory), 103, TrustLevel = VSShellInterop::__VSEDITORTRUSTLEVEL.ETL_AlwaysTrusted)]
	[VSShell::ProvideEditorExtension(typeof(IotDslEditorFactory), "." + Constants.DesignerFileExtension, 50)]
	[VSShell::ProvideEditorLogicalView(typeof(IotDslEditorFactory), "{7651A702-06E5-11D1-8EBD-00A0C90F26EA}")] // Designer logical view GUID i.e. VSConstants.LOGVIEWID_Designer
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.CSharpProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.VisualBasicProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::RegisterAsDslToolsEditor]
	[global::System.Runtime.InteropServices.ComVisible(true)]
	[DslShell::ProvideBindingPath]
	[DslShell::ProvideXmlEditorChooserBlockSxSWithXmlEditor(@"IotDsl", typeof(IotDslEditorFactory))]

	internal abstract partial class IotDslPackageBase : DslShell::ModelingPackage
	{
		protected global::Compañía.IotDsl.IotDslToolboxHelper toolboxHelper;	
		
		/// <summary>
		/// Initialization method called by the package base class when this package is loaded.
		/// </summary>
		protected override void Initialize()
		{
			base.Initialize();

			// Register the editor factory used to create the DSL editor.
			this.RegisterEditorFactory(new IotDslEditorFactory(this));
			
			// Initialize the toolbox helper
			toolboxHelper = new global::Compañía.IotDsl.IotDslToolboxHelper(this);

			// Create the command set that handles menu commands provided by this package.
			IotDslCommandSet commandSet = new IotDslCommandSet(this);
			commandSet.Initialize();
			
			// Create the command set that handles cut/copy/paste commands provided by this package.
			IotDslClipboardCommandSet clipboardCommandSet = new IotDslClipboardCommandSet(this);
			clipboardCommandSet.Initialize();
			
			// Register the model explorer tool window for this DSL.
			this.AddToolWindow(typeof(IotDslExplorerToolWindow));

			// Initialize Extension Registars
			// this is a partial method call
			this.InitializeExtensions();

			// Add dynamic toolbox items
			this.SetupDynamicToolbox();
		}

		/// <summary>
		/// Partial method to initialize ExtensionRegistrars (if any) in the DslPackage
		/// </summary>
		partial void InitializeExtensions();
		
		/// <summary>
		/// Returns any dynamic tool items for the designer
		/// </summary>
		/// <remarks>The default implementation is to return the list of items from the generated toolbox helper.</remarks>
		protected override global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			try
			{
				Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
				return toolboxHelper.CreateToolboxItems();
			}
			catch(global::System.Exception e)
			{
				global::System.Diagnostics.Debug.Fail("Exception thrown during toolbox item creation.  This may result in Package Load Failure:\r\n\r\n" + e);
				throw;
			}
		}
		
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		protected override object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
		
			// Retrieve the specified ToolboxItem from the DSL
			return toolboxHelper.GetToolboxItemData(itemId, format);
		}
	}

}

//
// Package attributes which may need to change are placed on the partial class below, rather than in the main include file.
//
namespace Compañía.IotDsl
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	[VSShell::ProvideMenuResource("1000.ctmenu", 1)]
	[VSShell::ProvideToolboxItems(1)]
	[global::Microsoft.VisualStudio.TextTemplating.VSHost.ProvideDirectiveProcessor(typeof(global::Compañía.IotDsl.IotDslDirectiveProcessor), global::Compañía.IotDsl.IotDslDirectiveProcessor.IotDslDirectiveProcessorName, "A directive processor that provides access to IotDsl files")]
	[global::System.Runtime.InteropServices.Guid(Constants.IotDslPackageId)]
	internal sealed partial class IotDslPackage : IotDslPackageBase
	{
	}
}